trigger:
- '*'

pool:
  name: Default
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    choco install visualstudio2019buildtools -y --ignore-checksums
    choco install python --version=3.9.0 -y
  displayName: 'Instalar herramientas necesarias (Visual Studio Build Tools y Python)'

- script: |
    npm config set python python3.9
    npm config set msvs_version 2019
  displayName: 'Configurar npm para usar Python y Visual Studio'

- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: sdk
    version: '6.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'
