trigger:
- '*'

pool:
  name: Default
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y python3 make g++ build-essential
  displayName: 'Instalar dependencias del sistema'

- task: UseNode@1
  displayName: 'Usar Node.js 16.x'
  inputs:
    versionSpec: '16.x'
    checkLatest: true

- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: sdk
    version: '6.x'

- script: |
    npm cache clean --force
    npm install
  displayName: 'Run npm install'

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'
